apiVersion: v1
kind: Service
metadata:
  name: websocket-service
  namespace: sre-copilot
  labels:
    app: websocket-service
spec:
  type: ClusterIP
  ports:
    - port: 8505
      targetPort: 8505
  selector:
    app: websocket-service
