apiVersion: v1
kind: Service
metadata:
  name: ai-service
  namespace: sre-copilot
  labels:
    app: ai-service
spec:
  type: ClusterIP
  ports:
    - port: 8503
      targetPort: 8503
  selector:
    app: ai-service
