apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: sre-copilot
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 5490
      targetPort: 5490
---
apiVersion: v1
kind: Endpoints
metadata:
  name: postgres
  namespace: sre-copilot
subsets:
  - addresses:
      - ip: 10.8.14.150
    ports:
      - port: 5490
