apiVersion: v1
kind: Service
metadata:
  name: metrics-collector-service
  namespace: sre-copilot
  labels:
    app: metrics-collector-service
spec:
  type: ClusterIP
  ports:
    - port: 8509
      targetPort: 8509
  selector:
    app: metrics-collector-service
