apiVersion: v1
kind: Service
metadata:
  name: alerting-service
  namespace: sre-copilot
  labels:
    app: alerting-service
spec:
  type: ClusterIP
  ports:
    - port: 8511
      targetPort: 8511
  selector:
    app: alerting-service
