apiVersion: v1
kind: Service
metadata:
  name: security-service
  namespace: sre-copilot
  labels:
    app: security-service
spec:
  type: ClusterIP
  ports:
    - port: 8513
      targetPort: 8513
  selector:
    app: security-service
